In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('task2.csv')
print (df)

               ID Segment type Segment Description Answer        Count  \
0     292890.8970          web     Meridian, Idaho     No     0.000000   
1     292887.9870          web     Meridian, Idaho     No     0.000000   
2     292894.0656       gender     Meridian, Idaho     No   499.173606   
3     292887.1180          web     Meridian, Idaho     No     0.000000   
4     292893.6561       gender     Meridian, Idaho     No   455.925963   
...           ...          ...                 ...    ...          ...   
1891  292887.5496          web     Meridian, Idaho     No     0.000000   
1892  292881.6932       mobile     Meridian, Idaho     No  1203.190399   
1893  292900.8499       gender                 NaN    NaN          NaN   
1894  292893.8600       gender     Meridian, Idaho     No  1149.529381   
1895  292890.2944          web     Meridian, Idaho     No     0.000000   

      Percentage  It became a relationship  
0       0.000000                       0.0  
1       0.000000     

In [3]:
df.replace(to_replace = np.nan, value = 0)

ID Segment type Segment Description Answer        Count  \
0     292890.8970          web     Meridian, Idaho     No     0.000000   
1     292887.9870          web     Meridian, Idaho     No     0.000000   
2     292894.0656       gender     Meridian, Idaho     No   499.173606   
3     292887.1180          web     Meridian, Idaho     No     0.000000   
4     292893.6561       gender     Meridian, Idaho     No   455.925963   
...           ...          ...                 ...    ...          ...   
1891  292887.5496          web     Meridian, Idaho     No     0.000000   
1892  292881.6932       mobile     Meridian, Idaho     No  1203.190399   
1893  292900.8499       gender                   0      0     0.000000   
1894  292893.8600       gender     Meridian, Idaho     No  1149.529381   
1895  292890.2944          web     Meridian, Idaho     No     0.000000   

      Percentage  It became a relationship  
0       0.000000                       0.0  
1       0.000000                       0.0  
2       0.225255                       0.0  
3       0.000000                       0.0  
4       0.211360                       0.0  
...          ...                       ...  
1891    0.000000                       0.0  
1892    0.312360                       0.0  
1893    0.000000                       0.0  
1894    0.488984                       0.0  
1895    0.000000                       0.0  

[1896 rows x 7 columns]

In [20]:
x = df.iloc[:, :-1].values
print(x)


[[292890.897 'web' 'Meridian, Idaho' 'No' 0.0 0.0]
 [292887.987 'web' 'Meridian, Idaho' 'No' 0.0 0.0]
 [292894.0656 'gender' 'Meridian, Idaho' 'No' 499.173606 0.225254764]
 ...
 [292900.8499 'gender' nan nan nan nan]
 [292893.86 'gender' 'Meridian, Idaho' 'No' 1149.529381 0.488984275]
 [292890.2944 'web' 'Meridian, Idaho' 'No' 0.0 0.0]]


In [43]:
y=df["It became a relationship"]
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1891    0.0
1892    0.0
1893    NaN
1894    0.0
1895    0.0
Name: It became a relationship, Length: 1896, dtype: float64

In [39]:
len(y)

1896

In [44]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: It became a relationship, dtype: float64

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 42)
y_test

1319    0.0
611     1.0
964     1.0
1316    0.0
585     0.0
       ... 
1341    1.0
570     0.0
1169    0.0
1037    0.0
1578    0.0
Name: It became a relationship, Length: 285, dtype: float64

In [46]:
len(y_test)

285

In [83]:
df=df.replace(to_replace="Yes",value=1)
df=df.replace(to_replace="I don't use Tinder",value=0)
df=df.replace(to_replace="web",value=0)
df=df.replace(to_replace="gender",value=1)
df=df.replace(to_replace="university",value=2)
df=df.replace(to_replace="mobile",value=3)
df=df.replace(to_replace="No",value=2)
df=df.replace(to_replace = np.nan, value = 0)

In [84]:
X=df.drop(columns="It became a relationship")
X=X.drop(columns="Segment Description")
X=X.drop(columns="ID")
y=df["It became a relationship"]
X.head()

Segment type  Answer       Count  Percentage
0             2     2.0    0.000000    0.000000
1             2     2.0    0.000000    0.000000
2             3     2.0  499.173606    0.225255
3             2     2.0    0.000000    0.000000
4             3     2.0  455.925963    0.211360

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 42)
y_test

1319    0.0
611     1.0
964     1.0
1316    0.0
585     0.0
       ... 
1341    1.0
570     0.0
1169    0.0
1037    0.0
1578    0.0
Name: It became a relationship, Length: 285, dtype: float64

In [87]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=1000)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9087719298245615

In [76]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

In [77]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [78]:
clf.score(X_test, y_test)

0.9157894736842105

In [89]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.887719298245614

In [90]:
from sklearn.linear_model import LogisticRegression
logistic_regression= LogisticRegression()
logistic_regression.fit(X_train,y_train)

LogisticRegression()

In [91]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [92]:
X_test

array([[ 1.58993324],
       [-0.94801236],
       [-1.4092475 ],
       [ 0.75824237],
       [ 1.58993324],
       [-1.71200035],
       [-0.66986636],
       [ 1.58993324],
       [ 0.63039814],
       [-1.81370916],
       [ 1.58993324],
       [-1.44270863],
       [-1.45162464],
       [-1.71238312],
       [-1.30283663],
       [-1.41667009],
       [-1.09889928],
       [-1.68279751],
       [ 0.54699286],
       [ 0.776913  ],
       [-1.05764866],
       [-1.184956  ],
       [ 1.58993324],
       [ 1.58993324],
       [ 0.9521374 ],
       [ 0.78083667],
       [-0.89615883],
       [ 1.58993324],
       [ 1.58993324],
       [ 1.58993324],
       [ 0.73497934],
       [ 1.58993324],
       [ 0.68807083],
       [-1.60360141],
       [-1.74747009],
       [ 0.75035207],
       [ 0.85708572],
       [ 0.83054261],
       [-0.62792228],
       [-1.6617049 ],
       [-1.76811771],
       [-0.9969306 ],
       [ 0.68116003],
       [ 1.58993324],
       [-0.9957337 ],
       [ 1

In [93]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)

In [94]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[131  52]
 [ 12  90]]
              precision    recall  f1-score   support

         0.0       0.92      0.72      0.80       183
         1.0       0.63      0.88      0.74       102

    accuracy                           0.78       285
   macro avg       0.77      0.80      0.77       285
weighted avg       0.82      0.78      0.78       285



In [98]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
clf.predict(X_test)

array([0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0.

In [99]:
y_test

1319    0.0
611     1.0
964     1.0
1316    0.0
585     0.0
       ... 
1341    1.0
570     0.0
1169    0.0
1037    0.0
1578    0.0
Name: It became a relationship, Length: 285, dtype: float64